### ISSUE TITLE
 deadlock in an UI application

### ISSUE THREAD

**Issue by Daemon6666** [orionstudt/DuoSecurity.Auth.Http#1]
ConfigureAwait(false) would be enough to solve the problem

**Comment by orionstudt** [comment]
Hi! You're right, that's an oversight. I will get that resolved when I have a moment.

**Comment by orionstudt** [comment]
Hey @Daemon6666, `1.0.1-beta` should now have `ConfigureAwait(false)` on all `async` calls and I also added `CancellationToken` support. Hope that works for you!
