### ISSUE TITLE
DateTime Offset issue while adding Date Header - Duo Any Request - 40105:Bad request timestamp

### ISSUE THREAD

**Issue by dileepgawriya** [orionstudt/DuoSecurity.Auth.Http#4]
Hi,

I'm sending requests from machine which uses IST time zone (+05:30). But while constructing `HttpRequestMessage` in file [DuoRequestBuilder.cs](https://github.com/orionstudt/DuoSecurity.Auth.Http/blob/cca853f32c8961a0d9c299bf7ed23eb9f2aec0dc/DuoSecurity.Auth.Http/Core/DuoRequestBuilder.cs#L29), it's calling a method `dateToRFC822(DateTime.Now)`  and this method only consider offset hours not minutes.

Because of it, If I'm sending request from +05:30 it will be changed to +05:00 and DUO API will always return error like **{\"code\": 40105, \"message\": \"Bad request timestamp\", \"stat\": \"FAIL\"}**, as DUO server only process requests which have max 60 seconds difference [Check Here](https://help.duo.com/s/article/3600).

**Comment by amitSahu9** [comment]
@dileepgawriya  how do we fix this?

**Comment by orionstudt** [comment]
Would using DateTimeOffset instead resolve this?

**Comment by amitSahu9** [comment]
@orionstudt  yes it might, can please resolve it.

**Comment by orionstudt** [comment]
This should resolve it: https://github.com/orionstudt/DuoSecurity.Auth.Http/commit/3f9b58bde4e297cfdf291d5ab9da8de59f7b25e1

With version 1.0.1 in the process of being listed: https://www.nuget.org/packages/DuoSecurity.Auth.Http/1.0.1

Let me know if this is still an issue after trying it with 1.0.1! It should be OK now.

**Comment by amitSahu9** [comment]
@orionstudt  its working fine,, Thank you ..
